### ISSUE TITLE
That's cool

### ISSUE THREAD

**Issue by ghost** [ScolderCreations/ScratchAPIGrabber#6]
Nice idea

**Comment by ghost** [comment]
I'm ForumHelperNanoPiex by the way.

**Comment by ScolderCreations** [comment]
Hello there. I know who you are. Unfortunately, this repo is not the best place to say stuff like “That’s cool”. Instead, you should give more detailed feedback, like “Hey, (feature) didn’t work” or “I like how you can (feature)”.
